### PR TITLE
Added the ability to copy selected blocks.

### PR DESCRIPTION
**Pull request by SimplyKyra**
Added a button when block is selected. When pressed it duplicates the current block and places it in the upper left corner. Size and opts are retained.

### CODE REVIEW

**Review by dynobo — CHANGES_REQUESTED** [review]
Thanks, @SimplyKyra, this is a very valuable feature!

The duplication itself works flawless, but the duplicated block will remain somehow "connected" and share the values for all options (even the non-global once). This is not very obvious, as the user needs to trigger a render on the second box to make the change visible:
Kooha-2021-10-29-07_53_19

Is it possible that L101 assigns the options by reference, instead by value? 
```javascript
newBlock.opts = originalBlock.opts;
```

Maybe it can be avoided by using [`Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) instead?

**Comment by SimplyKyra** [comment]
Good catch. It was a little bit more involved than I realized but now it seems to be working as expected. Thanks for the speedy review :)

**Review by dynobo — APPROVED** [review]

**Comment by dynobo** [comment]
Implements #51.

Thanks a lot, @SimplyKyra ! New release get's published, soon :-)

**Comment by dynobo** [comment]
Implements #51.

Thanks a lot, @SimplyKyra ! New release get's published, soon :-)

**Pull request merged**
